sonar.projectKey=inkwell-backend
sonar.projectName=Inkwell Backend
sonar.sources=.
sonar.exclusions=node_modules/**,coverage/**,.git/**,test/**
sonar.tests=test
sonar.test.inclusions=test/**/*.js
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.host.url=http://localhost:9000 
sonar.token=sqp_a8eb6737ca375bcd12b141f4d24cf5ac8a42d514
